package in.vidyalai.claude.sdk.types.message;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Known values of {@link MessageOrigin#kind()}.
 *
 * <p>
 * Newer CLI versions may emit kinds not listed here; those parse to a
 * {@code null} {@link MessageOrigin#kind()} with the wire string still
 * available from {@link MessageOrigin#kindValue()}. Treat anything
 * unrecognized as "not human".
 */
public enum MessageOriginKind {

    /** A prompt submitted by the application or an interactive user. */
    HUMAN("human"),

    /** A message that arrived on an MCP channel. */
    CHANNEL("channel"),

    /** A message relayed from a peer session or an in-process subagent. */
    PEER("peer"),

    /** A background-task notification, or a fired scheduled-task prompt. */
    TASK_NOTIFICATION("task-notification"),

    /** A turn injected by the coordinator of a multi-session workflow. */
    COORDINATOR("coordinator"),

    /** The CLI could not attribute the turn to any known source. */
    UNCLASSIFIED("unclassified"),

    /** A message from an observer attached to this session. */
    OBSERVER("observer"),

    /** A turn the session started on its own to continue previous work. */
    AUTO_CONTINUATION("auto-continuation"),

    /** An activity report generated by an observer. */
    OBSERVER_ACTIVITY("observer-activity");

    private final String value;

    MessageOriginKind(String value) {
        this.value = value;
    }

    /**
     * Returns the wire value of this kind.
     *
     * @return the value the CLI emits for this kind
     */
    @JsonValue
    public String getValue() {
        return value;
    }

    @Override
    public String toString() {
        return value;
    }

    /**
     * Resolves a wire value to a kind.
     *
     * @param value the wire value
     * @return the matching kind
     * @throws IllegalArgumentException if the value is not a known kind
     */
    public static MessageOriginKind fromValue(String value) {
        for (MessageOriginKind k : values()) {
            if (k.value.equals(value)) {
                return k;
            }
        }
        throw new IllegalArgumentException("Unknown MessageOriginKind: " + value);
    }

}
