package in.vidyalai.claude.sdk.types.message;

import java.util.Map;

import org.jspecify.annotations.Nullable;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Per-model token usage and cost breakdown, keyed by model string in
 * {@link ResultMessage#modelUsage()}.
 *
 * <p>
 * <b>JSON Naming Convention:</b> Unusually for CLI-received data, this type
 * uses {@code camelCase} JSON field names. The CLI passes the {@code modelUsage}
 * value through verbatim, so the keys match the TypeScript SDK's
 * {@code ModelUsage} shape rather than the {@code snake_case} used elsewhere on
 * {@link ResultMessage}. See {@link in.vidyalai.claude.sdk.types} package
 * documentation for the general convention.
 *
 * @param inputTokens              tokens sent to the model
 * @param outputTokens             tokens generated by the model
 * @param cacheReadInputTokens     tokens read from the prompt cache
 * @param cacheCreationInputTokens tokens written to the prompt cache
 * @param webSearchRequests        number of server-side web search requests
 * @param costUsd                  cost attributed to this model, in USD
 * @param contextWindow            the model's context window size in tokens
 * @param maxOutputTokens          the model's maximum output length in tokens
 * @param canonicalModel           canonical model id used for the pricing
 *                                 lookup (e.g. {@code "claude-opus-4-7"}). May
 *                                 differ from the raw model string this entry
 *                                 is keyed by (provider-specific ids, aliases).
 *                                 Null on CLI versions that do not emit it.
 * @param provider                 API provider that served this model
 *                                 ({@code "firstParty"}, {@code "bedrock"},
 *                                 {@code "vertex"}, {@code "foundry"},
 *                                 {@code "anthropicAws"},
 *                                 {@code "anthropicGoogleCloud"},
 *                                 {@code "mantle"}, {@code "gateway"}). Null on
 *                                 CLI versions that do not emit it.
 * @param raw                      full raw map from the CLI, including any
 *                                 fields not modeled above
 */
public record ModelUsage(
        @JsonProperty("inputTokens") long inputTokens,
        @JsonProperty("outputTokens") long outputTokens,
        @JsonProperty("cacheReadInputTokens") long cacheReadInputTokens,
        @JsonProperty("cacheCreationInputTokens") long cacheCreationInputTokens,
        @JsonProperty("webSearchRequests") long webSearchRequests,
        @JsonProperty("costUSD") double costUsd,
        @JsonProperty("contextWindow") long contextWindow,
        @JsonProperty("maxOutputTokens") long maxOutputTokens,
        @JsonProperty("canonicalModel") @Nullable String canonicalModel,
        @JsonProperty("provider") @Nullable String provider,
        @Nullable Map<String, Object> raw) {
}
