package in.vidyalai.claude.sdk.internal;

/**
 * SDK version information.
 *
 * <p>
 * This file is automatically generated during build from the Maven project
 * version.
 * Do not edit manually - changes will be overwritten.
 */
public final class SdkVersion {

    /**
     * The current SDK version, synchronized with pom.xml.
     */
    public static final String VERSION = "${project.version}";

    private SdkVersion() {
        throw new AssertionError("Utility class should not be instantiated");
    }

}
